// Perform Row actions
export const DELETE_STANDARD = 'DELETE_STANDARD'
export const INDENT_STANDARD = 'INDENT_STANDARD'
export const OUTDENT_STANDARD = 'OUTDENT_STANDARD'

export const MOVE_DOWN = 'MOVE_DOWN'
export const MOVE_UP = 'MOVE_UP'

export const ADD_NEW_STANDARD = 'ADD_NEW_STANDARD'
export const EDIT_STANDARD = 'EDIT_STANDARD'

export const SET_GLOBAL_STATE = 'SET_GLOBAL_STATE'